version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g npm@latest
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - Procfile
    - appspec.yml
  discard-paths: no 