#!/bin/bash

# Script to display all URLs needed for assignment screenshots
REGION="ap-southeast-2"

echo "=================================================="
echo "📸 AWS CONSOLE URLS FOR ASSIGNMENT SCREENSHOTS"
echo "=================================================="
echo ""
echo "Copy and paste these URLs into your browser:"
echo ""

echo "=== FIGURES 82-84: X-RAY CONFIGURATION ==="
echo "1. Lambda with X-Ray Enabled:"
echo "   https://$REGION.console.aws.amazon.com/lambda/home?region=$REGION#/functions/college-safe-serverless-dev-auth?tab=monitoring"
echo ""
echo "2. X-Ray Service Map:"
echo "   https://$REGION.console.aws.amazon.com/xray/home?region=$REGION#/service-map"
echo ""
echo "3. X-Ray Traces:"
echo "   https://$REGION.console.aws.amazon.com/xray/home?region=$REGION#/traces"
echo ""

echo "=== FIGURES 85-86: CLOUDWATCH MONITORING ==="
echo "4. CloudWatch Metrics (CPU Utilization):"
echo "   https://$REGION.console.aws.amazon.com/cloudwatch/home?region=$REGION#metricsV2:graph=~()"
echo ""
echo "5. CloudWatch Dashboard:"
echo "   https://$REGION.console.aws.amazon.com/cloudwatch/home?region=$REGION#dashboards:name=college-safe-comprehensive-monitoring"
echo ""
echo "6. CloudWatch Logs:"
echo "   https://$REGION.console.aws.amazon.com/cloudwatch/home?region=$REGION#logsV2:log-groups"
echo ""

echo "=== FIGURES 57-60: LAMBDA FUNCTIONS ==="
echo "7. Lambda Functions List:"
echo "   https://$REGION.console.aws.amazon.com/lambda/home?region=$REGION#/functions"
echo ""

echo "=== FIGURES 52-56: DYNAMODB ==="
echo "8. DynamoDB Tables:"
echo "   https://$REGION.console.aws.amazon.com/dynamodbv2/home?region=$REGION#tables"
echo ""

echo "=== FIGURES 28-31: S3 BUCKETS ==="
echo "9. S3 Buckets:"
echo "   https://s3.console.aws.amazon.com/s3/home?region=$REGION"
echo ""

echo "=== FIGURES 62-69: API GATEWAY ==="
echo "10. API Gateway:"
echo "    https://$REGION.console.aws.amazon.com/apigateway/home?region=$REGION#/apis"
echo ""

echo "=== FIGURES 70-76: SNS ==="
echo "11. SNS Topics:"
echo "    https://$REGION.console.aws.amazon.com/sns/v3/home?region=$REGION#/topics"
echo ""

echo "=== ADDITIONAL RESOURCES ==="
echo "12. CloudWatch Alarms:"
echo "    https://$REGION.console.aws.amazon.com/cloudwatch/home?region=$REGION#alarmsV2:"
echo ""
echo "13. IAM Roles (for Lambda execution role):"
echo "    https://console.aws.amazon.com/iam/home#/roles"
echo ""

echo "=================================================="
echo "📝 SCREENSHOT INSTRUCTIONS:"
echo "=================================================="
echo ""
echo "For Figure 82 (Enabling X-Ray):"
echo "  → Open Lambda function → Configuration → Monitoring and operations tools"
echo ""
echo "For Figure 83 (X-Ray Traces):"
echo "  → Open X-Ray Traces link above"
echo "  → You should see recent traces from the test invocations"
echo ""
echo "For Figure 84 (Trace Details):"
echo "  → Click on any trace ID from the traces list"
echo "  → Shows the trace map and timeline"
echo ""
echo "For Figure 85 (CPU/Metrics):"
echo "  → Open CloudWatch Metrics"
echo "  → Navigate to Lambda → By Function Name"
echo "  → Select Duration or Invocations metric"
echo ""
echo "For Figure 86 (Lambda Logs):"
echo "  → Open CloudWatch Logs"
echo "  → Click on /aws/lambda/college-safe-serverless-dev-* log group"
echo "  → View recent log streams"
echo ""

echo "✅ All resources are configured and ready for screenshots!"
echo "📌 Remember to wait 1-2 minutes after generating data for metrics to appear."

